# Generated by Django 4.2 on 2026-01-31 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(help_text='ID único del canal de YouTube', max_length=50, unique=True, verbose_name='ID de YouTube')),
                ('nombre_canal', models.CharField(help_text='Nombre público del canal de YouTube', max_length=200, verbose_name='Nombre del canal')),
                ('email', models.EmailField(blank=True, help_text='Email de la cuenta de Google (puede estar vacío por privacidad)', max_length=254, verbose_name='Email asociado')),
                ('foto_perfil', models.URLField(blank=True, help_text='URL de la imagen de perfil del canal', max_length=500, verbose_name='Foto de perfil')),
                ('access_token', models.TextField(help_text='Token de acceso OAuth 2.0 para YouTube API', verbose_name='Token de acceso')),
                ('refresh_token', models.TextField(blank=True, help_text='Token de refresco para obtener nuevos access tokens', verbose_name='Token de refresco')),
                ('token_expira', models.DateTimeField(blank=True, help_text='Fecha y hora en que expira el token de acceso', null=True, verbose_name='Token expira')),
                ('suscriptores', models.IntegerField(default=0, help_text='Número de suscriptores del canal', verbose_name='Suscriptores')),
                ('videos_publicados', models.IntegerField(default=0, help_text='Número total de videos publicados en el canal', verbose_name='Videos publicados')),
                ('vistas_totales', models.BigIntegerField(default=0, help_text='Número total de vistas de todos los videos del canal', verbose_name='Vistas totales')),
                ('fecha_vinculacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de vinculación')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('descripcion_canal', models.TextField(blank=True, help_text='Descripción pública del canal', verbose_name='Descripción del canal')),
                ('url_canal', models.URLField(blank=True, help_text='URL completa del canal de YouTube', max_length=500, verbose_name='URL del canal')),
                ('monitoreo_activo', models.BooleanField(default=True, help_text='Indica si se deben monitorear las estadísticas automáticamente', verbose_name='Monitoreo activo')),
                ('frecuencia_actualizacion', models.IntegerField(default=60, help_text='Cada cuántos minutos se actualizan las estadísticas', verbose_name='Frecuencia de actualización (minutos)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_account', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Django')),
            ],
            options={
                'verbose_name': 'Cuenta de YouTube',
                'verbose_name_plural': 'Cuentas de YouTube',
                'ordering': ['-fecha_vinculacion'],
            },
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_video_id', models.CharField(help_text='ID único del video (ej: dQw4w9WgXcQ)', max_length=20, unique=True, verbose_name='ID del video en YouTube')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título del video')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del video')),
                ('thumbnail_default', models.URLField(blank=True, max_length=500, verbose_name='Thumbnail (default)')),
                ('thumbnail_medium', models.URLField(blank=True, max_length=500, verbose_name='Thumbnail (medium)')),
                ('thumbnail_high', models.URLField(blank=True, max_length=500, verbose_name='Thumbnail (high)')),
                ('thumbnail_maxres', models.URLField(blank=True, max_length=500, verbose_name='Thumbnail (maxres)')),
                ('duracion_segundos', models.IntegerField(default=0, verbose_name='Duración (segundos)')),
                ('estado', models.CharField(choices=[('public', 'Público'), ('private', 'Privado'), ('unlisted', 'No listado')], default='public', max_length=10, verbose_name='Estado de visibilidad')),
                ('categoria_id', models.CharField(blank=True, max_length=20, verbose_name='ID de categoría')),
                ('etiquetas', models.TextField(blank=True, help_text='Etiquetas separadas por comas', verbose_name='Etiquetas')),
                ('vistas', models.BigIntegerField(default=0, verbose_name='Vistas')),
                ('likes', models.IntegerField(default=0, verbose_name='Me gusta')),
                ('dislikes', models.IntegerField(default=0, verbose_name='No me gusta')),
                ('comentarios', models.IntegerField(default=0, verbose_name='Comentarios')),
                ('favoritos', models.IntegerField(default=0, verbose_name='Favoritos')),
                ('fecha_publicacion', models.DateTimeField(verbose_name='Fecha de publicación en YouTube')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida a nuestro sistema')),
                ('monitoreo_activo', models.BooleanField(default=True, verbose_name='Monitoreo activo')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización de estadísticas')),
                ('youtube_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='videos.youtubeaccount', verbose_name='Cuenta de YouTube')),
            ],
            options={
                'verbose_name': 'Video de YouTube',
                'verbose_name_plural': 'Videos de YouTube',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='YouTubeAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(verbose_name='Fecha del registro')),
                ('suscriptores', models.IntegerField(default=0, verbose_name='Suscriptores')),
                ('vistas_totales', models.BigIntegerField(default=0, verbose_name='Vistas totales')),
                ('videos_publicados', models.IntegerField(default=0, verbose_name='Videos publicados')),
                ('crecimiento_suscriptores', models.IntegerField(default=0, verbose_name='Crecimiento de suscriptores')),
                ('crecimiento_vistas', models.BigIntegerField(default=0, verbose_name='Crecimiento de vistas')),
                ('youtube_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='videos.youtubeaccount', verbose_name='Cuenta de YouTube')),
            ],
            options={
                'verbose_name': 'Análisis de YouTube',
                'verbose_name_plural': 'Análisis de YouTube',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('url_video', models.URLField()),
                ('url_thumbnail', models.URLField()),
                ('canal_id', models.CharField(max_length=50)),
                ('canal_nombre', models.CharField(max_length=200)),
                ('duracion', models.CharField(blank=True, max_length=20)),
                ('fecha_publicacion', models.DateTimeField()),
                ('vistas', models.BigIntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('comentarios', models.IntegerField(default=0)),
                ('categoria', models.CharField(choices=[('programacion', 'Programación'), ('bases_datos', 'Bases de Datos'), ('redes', 'Redes'), ('seguridad', 'Seguridad'), ('otro', 'Otro')], max_length=50)),
                ('etiquetas', models.CharField(blank=True, max_length=500)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('agregado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Videos',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('publica', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('videos', models.ManyToManyField(related_name='playlists', to='videos.video')),
            ],
        ),
        migrations.CreateModel(
            name='OAuthErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_error', models.CharField(max_length=100, verbose_name='Tipo de error')),
                ('descripcion', models.TextField(verbose_name='Descripción del error')),
                ('url_solicitud', models.URLField(blank=True, max_length=500, verbose_name='URL de la solicitud')),
                ('respuesta_api', models.TextField(blank=True, verbose_name='Respuesta de la API')),
                ('fecha_error', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del error')),
                ('resuelto', models.BooleanField(default=False, verbose_name='¿Resuelto?')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario relacionado')),
            ],
            options={
                'verbose_name': 'Log de error OAuth',
                'verbose_name_plural': 'Logs de errores OAuth',
                'ordering': ['-fecha_error'],
            },
        ),
        migrations.AddIndex(
            model_name='youtubevideo',
            index=models.Index(fields=['youtube_video_id'], name='videos_yout_youtube_65b759_idx'),
        ),
        migrations.AddIndex(
            model_name='youtubevideo',
            index=models.Index(fields=['youtube_account', 'fecha_publicacion'], name='videos_yout_youtube_d4a41d_idx'),
        ),
        migrations.AddIndex(
            model_name='youtubevideo',
            index=models.Index(fields=['monitoreo_activo'], name='videos_yout_monitor_867d0d_idx'),
        ),
        migrations.AddIndex(
            model_name='youtubeanalytics',
            index=models.Index(fields=['youtube_account', 'fecha_registro'], name='videos_yout_youtube_589ce0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='youtubeanalytics',
            unique_together={('youtube_account', 'fecha_registro')},
        ),
        migrations.AddIndex(
            model_name='youtubeaccount',
            index=models.Index(fields=['youtube_id'], name='videos_yout_youtube_f75218_idx'),
        ),
        migrations.AddIndex(
            model_name='youtubeaccount',
            index=models.Index(fields=['user'], name='videos_yout_user_id_f6e2df_idx'),
        ),
        migrations.AddIndex(
            model_name='youtubeaccount',
            index=models.Index(fields=['fecha_vinculacion'], name='videos_yout_fecha_v_1c9e63_idx'),
        ),
    ]
