# Generated by Django 4.2 on 2026-01-31 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSubido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_video_id', models.CharField(max_length=20, unique=True, verbose_name='ID del video en YouTube')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título del video')),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('uploading', 'Subiendo'), ('processing', 'Procesando'), ('published', 'Publicado'), ('failed', 'Fallido')], default='pending', max_length=20, verbose_name='Estado de subida')),
                ('archivo_path', models.CharField(help_text='Ruta local del archivo de video', max_length=500, verbose_name='Ruta del archivo')),
                ('archivo_size', models.BigIntegerField(default=0, verbose_name='Tamaño del archivo (bytes)')),
                ('duracion', models.IntegerField(default=0, verbose_name='Duración (segundos)')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('etiquetas', models.TextField(blank=True, help_text='Separadas por comas', verbose_name='Etiquetas')),
                ('categoria_id', models.CharField(default='22', help_text='22 por defecto (People & Blogs)', max_length=20, verbose_name='ID de categoría YouTube')),
                ('privacidad', models.CharField(choices=[('public', 'Público'), ('private', 'Privado'), ('unlisted', 'No listado')], default='private', max_length=10, verbose_name='Configuración de privacidad')),
                ('inicio_subida', models.DateTimeField(blank=True, null=True, verbose_name='Inicio de subida')),
                ('fin_subida', models.DateTimeField(blank=True, null=True, verbose_name='Fin de subida')),
                ('mensaje_error', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('youtube_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_subidos', to='videos.youtubeaccount', verbose_name='Cuenta de YouTube')),
            ],
            options={
                'verbose_name': 'Video subido',
                'verbose_name_plural': 'Videos subidos',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='BusquedaVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=300, verbose_name='Término de búsqueda')),
                ('resultado_count', models.IntegerField(default=0, verbose_name='Número de resultados')),
                ('parametros_busqueda', models.JSONField(default=dict, help_text='Parámetros adicionales de búsqueda en formato JSON', verbose_name='Parámetros de búsqueda')),
                ('fecha_busqueda', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de búsqueda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='busquedas_videos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Búsqueda de video',
                'verbose_name_plural': 'Búsquedas de videos',
                'ordering': ['-fecha_busqueda'],
            },
        ),
        migrations.AddIndex(
            model_name='videosubido',
            index=models.Index(fields=['youtube_account', 'estado'], name='videos_vide_youtube_84d38e_idx'),
        ),
        migrations.AddIndex(
            model_name='videosubido',
            index=models.Index(fields=['estado'], name='videos_vide_estado_3bd328_idx'),
        ),
        migrations.AddIndex(
            model_name='videosubido',
            index=models.Index(fields=['creado'], name='videos_vide_creado_077999_idx'),
        ),
        migrations.AddIndex(
            model_name='busquedavideo',
            index=models.Index(fields=['usuario', 'fecha_busqueda'], name='videos_busq_usuario_90453f_idx'),
        ),
        migrations.AddIndex(
            model_name='busquedavideo',
            index=models.Index(fields=['query'], name='videos_busq_query_40a3d9_idx'),
        ),
    ]
