# Generated by Django 4.2 on 2026-01-31 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0002_videosubido_busquedavideo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de agregado')),
                ('visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('favorito', models.BooleanField(default=False, verbose_name='Favorito')),
                ('notas', models.TextField(blank=True, verbose_name='Notas personales')),
                ('usuario_propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_gestionados', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='videos.video', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Gestor de Video',
                'verbose_name_plural': 'Gestores de Video',
                'ordering': ['-fecha_agregado'],
            },
        ),
        migrations.CreateModel(
            name='EstadisticasVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del registro')),
                ('vistas', models.IntegerField(default=0, verbose_name='Vistas del día')),
                ('likes', models.IntegerField(default=0, verbose_name='Likes del día')),
                ('comentarios', models.IntegerField(default=0, verbose_name='Comentarios del día')),
                ('crecimiento_vistas', models.IntegerField(default=0, verbose_name='Crecimiento de vistas')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas_diarias', to='videos.video', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Estadística Diaria de Video',
                'verbose_name_plural': 'Estadísticas Diarias de Video',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='videomanager',
            index=models.Index(fields=['usuario_propietario', 'favorito'], name='videos_vide_usuario_8c8df1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='estadisticasvideo',
            unique_together={('video', 'fecha')},
        ),
    ]
