# Generated by Django 4.2 on 2026-01-31 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0003_videomanager_estadisticasvideo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGuardado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(help_text='Ej: dQw4w9WgXcQ', max_length=100, verbose_name='ID del video en YouTube')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título del video')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('canal_nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del canal')),
                ('canal_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID del canal')),
                ('url_thumbnail', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL del thumbnail')),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de publicación en YouTube')),
                ('vistas', models.BigIntegerField(default=0, verbose_name='Vistas')),
                ('likes', models.IntegerField(default=0, verbose_name='Likes')),
                ('comentarios', models.IntegerField(default=0, verbose_name='Comentarios')),
                ('duracion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Duración')),
                ('categoria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoría')),
                ('etiquetas', models.TextField(blank=True, null=True, verbose_name='Etiquetas (separadas por comas)')),
                ('fecha_guardado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de guardado')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('favorito', models.BooleanField(default=False, verbose_name='Favorito')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas personales')),
                ('visto', models.BooleanField(default=False, verbose_name='¿Visto?')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos_guardados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Video Guardado',
                'verbose_name_plural': 'Videos Guardados',
                'ordering': ['-fecha_guardado'],
            },
        ),
        migrations.CreateModel(
            name='HistorialBusqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=300, verbose_name='Término de búsqueda')),
                ('parametros', models.JSONField(default=dict, help_text='Filtros, orden, etc.', verbose_name='Parámetros de búsqueda')),
                ('resultados_encontrados', models.IntegerField(default=0, verbose_name='Resultados encontrados')),
                ('fecha_busqueda', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de búsqueda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_busquedas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Búsqueda',
                'verbose_name_plural': 'Historial de Búsquedas',
                'ordering': ['-fecha_busqueda'],
            },
        ),
        migrations.AddIndex(
            model_name='videoguardado',
            index=models.Index(fields=['usuario', 'fecha_guardado'], name='videos_vide_usuario_3054e4_idx'),
        ),
        migrations.AddIndex(
            model_name='videoguardado',
            index=models.Index(fields=['video_id'], name='videos_vide_video_i_a18892_idx'),
        ),
        migrations.AddIndex(
            model_name='videoguardado',
            index=models.Index(fields=['favorito'], name='videos_vide_favorit_b5a6b3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='videoguardado',
            unique_together={('video_id', 'usuario')},
        ),
    ]
